import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "./components/Home/Navigation/ResponsiveNav";
import Scroll from "./components/Helper/Sroll";

// Import and configure the Plus Jakarta Sans font
const font = Plus_Jakarta_Sans({ 
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin']
});

// Define metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component to define the structure of your application
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ResponsiveNav />
        {children}
        <Scroll/>
      </body>
    </html>
  );
}
